### PR TITLE
Hanami plugin

### PR DESCRIPTION
**Pull request by jodosha**
Use `better_errors` and `binding_of_caller` gems and package them as an Hanami plugin.

From my Hanami project (`bookshelf`) the only thing that I need to do is:

```ruby
# Gemfile
group :development do
  gem "hanami-webconsole"
end
```

### CODE REVIEW

**Comment by davydovanton** [comment]
let's merge it? I'm checking DNS rebinding issue for better error

**Comment by davydovanton** [comment]
@jodosha Checked DNS rebinding error with latest better error.

## Step to reproduce
0. initialize a new hanami app (or use exist one)

1. add better error to hanami project:
```ruby
# Gemfile
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end


# config.ru
if defined?(BetterErrors)
  use BetterErrors::Middleware
  BetterErrors.application_root = __dir__
end
```

2. start hanami server on `3000` port:
```
$ bundle exec hanami s -p 3000
```

3. open http://dnsrebinder.net and wait 2 minutes

### Result

I got this request:
```
[cookie_box] [INFO] [2018-02-06 00:30:57 +0300] HTTP/1.1 GET 404 127.0.0.1 /not_found 1386 {} 0.004197
```

---------

I think we can skip DNS binding protection from our side and start thing about other features of `hanami-devconsole`

/cc @hanami/core

**Comment by jodosha** [comment]
@davydovanton Thanks for checking. From your comment isn't clear if the `better_errors` is still vulnerable or not.

If it still is, we can build the DNS binding protection in a separated PR.

**Comment by davydovanton** [comment]
Oh, I forgot to add. Better error has protection now. We can forgot about own dns protection

**Comment by jodosha** [comment]
@davydovanton Thanks for the clarification!

**Pull request merged**
